// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDh0PPB6PLwAnO2bgxdF4iOSEL9TxAIino',
    appId: '1:755255869620:web:4a3153e6a3aaa867bed7e1',
    messagingSenderId: '755255869620',
    projectId: 'corporate-threat-detection',
    authDomain: 'corporate-threat-detection.firebaseapp.com',
    storageBucket: 'corporate-threat-detection.firebasestorage.app',
    measurementId: 'G-ZTDQ05TSR6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuyAwr2gtrlRx60xcimCY6F6aF71ZBShk',
    appId: '1:755255869620:android:000d287a8a540df9bed7e1',
    messagingSenderId: '755255869620',
    projectId: 'corporate-threat-detection',
    storageBucket: 'corporate-threat-detection.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjQxG4VueBvSTXwTxTFuSDo5aPBwm_fW0',
    appId: '1:755255869620:ios:263dc9c32206b96fbed7e1',
    messagingSenderId: '755255869620',
    projectId: 'corporate-threat-detection',
    storageBucket: 'corporate-threat-detection.firebasestorage.app',
    iosBundleId: 'com.example.corporateThreatDetection',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjQxG4VueBvSTXwTxTFuSDo5aPBwm_fW0',
    appId: '1:755255869620:ios:263dc9c32206b96fbed7e1',
    messagingSenderId: '755255869620',
    projectId: 'corporate-threat-detection',
    storageBucket: 'corporate-threat-detection.firebasestorage.app',
    iosBundleId: 'com.example.corporateThreatDetection',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDh0PPB6PLwAnO2bgxdF4iOSEL9TxAIino',
    appId: '1:755255869620:web:4ae6a71e24d80806bed7e1',
    messagingSenderId: '755255869620',
    projectId: 'corporate-threat-detection',
    authDomain: 'corporate-threat-detection.firebaseapp.com',
    storageBucket: 'corporate-threat-detection.firebasestorage.app',
    measurementId: 'G-6ZX10ZPKL6',
  );
}
